float = "Float64"

[csv]
dateformat = "dd.mm.yyyy"
delim = ";"

[solver]
linalg = "sparse"
reorder = "amd"
maxiters = 10
P_tol = 1e-7
r_tol = 0.00001

[optimizer]
package = "NLopt"
scaling = "sigmoid"
maxiters = 100

  [optimizer.NLopt]
  active = [
  "LD_LBFGS",
  "LD_TNEWTON_PRECOND_RESTART",
  "LD_MMA",
  "LD_CCSAQ",
  "LD_VAR2",
  "LD_VAR1"
]

[optimizer.NLopt.methods.LD_LBFGS]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

[optimizer.NLopt.methods.LD_TNEWTON_PRECOND_RESTART]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

[optimizer.NLopt.methods.LD_MMA]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

[optimizer.NLopt.methods.LD_CCSAQ]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

[optimizer.NLopt.methods.LD_SLSQP]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

[optimizer.NLopt.methods.LD_VAR2]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

[optimizer.NLopt.methods.LD_VAR1]
ftol_rel = 1e-12
ftol_abs = 1e-12
xtol_rel = 1e-12
xtol_abs = 1e-12
maxeval = 1_000

  [optimizer.SciPy]
  active = [ "L-BFGS-B", "TNC" ]

[optimizer.SciPy.methods.L-BFGS-B]
maxiter = 500
disp = 0
ftol = 1e-12
maxfun = 10_000_000_000
maxcor = 50
maxls = 100

[optimizer.SciPy.methods.SLSQP]
maxiter = 500
ftol = 1e-12
disp = 0

[optimizer.SciPy.methods.TNC]
maxiter = 1_000
stepmx = 100
ftol = 1e-12
gtol = 1e-12
xtol = 1e-12
disp = 0

[optimizer.SciPy.methods.trust-constr]
maxiter = 500
gtol = 1e-12
xtol = 1e-12
barrier_tol = 1e-12
disp = 0

[target_fun]
alpha_resp = 1
alpha_bhp = 0.01
alpha_inj = 0.01
alpha_lb = 10
alpha_ub = 10
alpha_l2 = 1